from typing import Protocol

from shared.price_refresh_service.type import JobStats, ProductData


class ProductRepository(Protocol):
    def get_product(self, product_id: int) -> ProductData: ...
    def update_product_price(self, product_id: int, price, mrp) -> None: ...


class JobRepository(Protocol):
    def create_job(self, job_id: str, system: str, total: int) -> None: ...
    def mark_processing(self, job_id: str) -> None: ...
    def sync_from_redis(self, job_id: str, redis_data: dict) -> None: ...
    def get_stats(self, system: str) -> JobStats: ...
