# Generated by Django 4.2.30 on 2026-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('system', models.CharField(max_length=8)),
                ('total', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('wall_time_ms', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform_identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_refreshed_at', models.DateTimeField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform_identifier'], name='shared_prod_platfor_468259_idx')],
            },
        ),
    ]
